// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Invite struct {
	ID              int64          `json:"id"`
	Uuid            string         `json:"uuid"`
	Name            string         `json:"name"`
	MaxAdults       int64          `json:"max_adults"`
	MaxKids         int64          `json:"max_kids"`
	Attending       sql.NullBool   `json:"attending"`
	AdultCount      sql.NullInt64  `json:"adult_count"`
	KidCount        sql.NullInt64  `json:"kid_count"`
	DietaryInfo     sql.NullString `json:"dietary_info"`
	MessageForUs    sql.NullString `json:"message_for_us"`
	SongRequest     sql.NullString `json:"song_request"`
	ResponseAt      sql.NullTime   `json:"response_at"`
	ResponseCountry sql.NullString `json:"response_country"`
	SheetRow        sql.NullInt64  `json:"sheet_row"`
	SyncedAt        sql.NullTime   `json:"synced_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}
