// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.deleteInviteStmt, err = db.PrepareContext(ctx, DeleteInvite); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteInvite: %w", err)
	}
	if q.getInviteByInviteCodeStmt, err = db.PrepareContext(ctx, GetInviteByInviteCode); err != nil {
		return nil, fmt.Errorf("error preparing query GetInviteByInviteCode: %w", err)
	}
	if q.getPendingSyncInvitesStmt, err = db.PrepareContext(ctx, GetPendingSyncInvites); err != nil {
		return nil, fmt.Errorf("error preparing query GetPendingSyncInvites: %w", err)
	}
	if q.markInviteSyncedStmt, err = db.PrepareContext(ctx, MarkInviteSynced); err != nil {
		return nil, fmt.Errorf("error preparing query MarkInviteSynced: %w", err)
	}
	if q.updateRSVPStmt, err = db.PrepareContext(ctx, UpdateRSVP); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateRSVP: %w", err)
	}
	if q.upsertInviteStmt, err = db.PrepareContext(ctx, UpsertInvite); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertInvite: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.deleteInviteStmt != nil {
		if cerr := q.deleteInviteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteInviteStmt: %w", cerr)
		}
	}
	if q.getInviteByInviteCodeStmt != nil {
		if cerr := q.getInviteByInviteCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getInviteByInviteCodeStmt: %w", cerr)
		}
	}
	if q.getPendingSyncInvitesStmt != nil {
		if cerr := q.getPendingSyncInvitesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPendingSyncInvitesStmt: %w", cerr)
		}
	}
	if q.markInviteSyncedStmt != nil {
		if cerr := q.markInviteSyncedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markInviteSyncedStmt: %w", cerr)
		}
	}
	if q.updateRSVPStmt != nil {
		if cerr := q.updateRSVPStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateRSVPStmt: %w", cerr)
		}
	}
	if q.upsertInviteStmt != nil {
		if cerr := q.upsertInviteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertInviteStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                        DBTX
	tx                        *sql.Tx
	deleteInviteStmt          *sql.Stmt
	getInviteByInviteCodeStmt *sql.Stmt
	getPendingSyncInvitesStmt *sql.Stmt
	markInviteSyncedStmt      *sql.Stmt
	updateRSVPStmt            *sql.Stmt
	upsertInviteStmt          *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                        tx,
		tx:                        tx,
		deleteInviteStmt:          q.deleteInviteStmt,
		getInviteByInviteCodeStmt: q.getInviteByInviteCodeStmt,
		getPendingSyncInvitesStmt: q.getPendingSyncInvitesStmt,
		markInviteSyncedStmt:      q.markInviteSyncedStmt,
		updateRSVPStmt:            q.updateRSVPStmt,
		upsertInviteStmt:          q.upsertInviteStmt,
	}
}
