// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"time"
)

type Invite struct {
	InviteCode      string     `json:"invite_code"`
	Name            string     `json:"name"`
	MaxAdults       int64      `json:"max_adults"`
	MaxKids         int64      `json:"max_kids"`
	ConfirmedAdults int64      `json:"confirmed_adults"`
	ConfirmedKids   int64      `json:"confirmed_kids"`
	DietaryInfo     string     `json:"dietary_info"`
	MessageForUs    string     `json:"message_for_us"`
	SongRequest     string     `json:"song_request"`
	ResponseAt      *time.Time `json:"response_at"`
	SheetRow        *int64     `json:"sheet_row"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

type ScheduleEvent struct {
	ID            int64     `json:"id"`
	StartTime     string    `json:"start_time"`
	EndTime       *string   `json:"end_time"`
	EventNameEs   string    `json:"event_name_es"`
	EventNameEn   string    `json:"event_name_en"`
	EventNameCa   string    `json:"event_name_ca"`
	Location      string    `json:"location"`
	DescriptionEs string    `json:"description_es"`
	DescriptionEn string    `json:"description_en"`
	DescriptionCa string    `json:"description_ca"`
	UpdatedAt     time.Time `json:"updated_at"`
}
