// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"time"
)

type Invite struct {
	InviteCode      string     `json:"invite_code"`
	Name            string     `json:"name"`
	MaxAdults       int64      `json:"max_adults"`
	MaxKids         int64      `json:"max_kids"`
	ConfirmedAdults int64      `json:"confirmed_adults"`
	ConfirmedKids   int64      `json:"confirmed_kids"`
	DietaryInfo     string     `json:"dietary_info"`
	MessageForUs    string     `json:"message_for_us"`
	SongRequest     string     `json:"song_request"`
	ResponseAt      *time.Time `json:"response_at"`
	ResponseCountry string     `json:"response_country"`
	SheetRow        *int64     `json:"sheet_row"`
	SyncedAt        *time.Time `json:"synced_at"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}
