// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
	"time"
)

const CountInvites = `-- name: CountInvites :one
SELECT COUNT(*) FROM invites
`

// CountInvites
//
//	SELECT COUNT(*) FROM invites
func (q *Queries) CountInvites(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countInvitesStmt, CountInvites)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const DeleteAllScheduleEvents = `-- name: DeleteAllScheduleEvents :exec
DELETE FROM schedule_events
`

// Clears all schedule events before a full re-sync from sheet.
//
//	DELETE FROM schedule_events
func (q *Queries) DeleteAllScheduleEvents(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteAllScheduleEventsStmt, DeleteAllScheduleEvents)
	return err
}

const DeleteInvite = `-- name: DeleteInvite :exec
DELETE FROM invites
WHERE invite_code = ?
`

// HARD DELETE: This permanently removes the row.
//
//	DELETE FROM invites
//	WHERE invite_code = ?
func (q *Queries) DeleteInvite(ctx context.Context, inviteCode string) error {
	_, err := q.exec(ctx, q.deleteInviteStmt, DeleteInvite, inviteCode)
	return err
}

const GetInviteByInviteCode = `-- name: GetInviteByInviteCode :one
SELECT invite_code, name, max_adults, max_kids, confirmed_adults, confirmed_kids, dietary_info, message_for_us, song_request, response_at, sheet_row, location, travel_bus_to, travel_pickup, travel_arrival_flight, travel_bus_return, travel_hotel, travel_notes, travel_cocktail, travel_brunch, travel_return_detail, travel_updated_at, created_at, updated_at FROM invites WHERE invite_code = ?
`

// GetInviteByInviteCode
//
//	SELECT invite_code, name, max_adults, max_kids, confirmed_adults, confirmed_kids, dietary_info, message_for_us, song_request, response_at, sheet_row, location, travel_bus_to, travel_pickup, travel_arrival_flight, travel_bus_return, travel_hotel, travel_notes, travel_cocktail, travel_brunch, travel_return_detail, travel_updated_at, created_at, updated_at FROM invites WHERE invite_code = ?
func (q *Queries) GetInviteByInviteCode(ctx context.Context, inviteCode string) (*Invite, error) {
	row := q.queryRow(ctx, q.getInviteByInviteCodeStmt, GetInviteByInviteCode, inviteCode)
	var i Invite
	err := row.Scan(
		&i.InviteCode,
		&i.Name,
		&i.MaxAdults,
		&i.MaxKids,
		&i.ConfirmedAdults,
		&i.ConfirmedKids,
		&i.DietaryInfo,
		&i.MessageForUs,
		&i.SongRequest,
		&i.ResponseAt,
		&i.SheetRow,
		&i.Location,
		&i.TravelBusTo,
		&i.TravelPickup,
		&i.TravelArrivalFlight,
		&i.TravelBusReturn,
		&i.TravelHotel,
		&i.TravelNotes,
		&i.TravelCocktail,
		&i.TravelBrunch,
		&i.TravelReturnDetail,
		&i.TravelUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetPendingSyncInvites = `-- name: GetPendingSyncInvites :many
SELECT invite_code, name, max_adults, max_kids, confirmed_adults, confirmed_kids, dietary_info, message_for_us, song_request, response_at, sheet_row, location, travel_bus_to, travel_pickup, travel_arrival_flight, travel_bus_return, travel_hotel, travel_notes, travel_cocktail, travel_brunch, travel_return_detail, travel_updated_at, created_at, updated_at FROM invites
WHERE response_at IS NOT NULL
  AND datetime(response_at) > datetime(updated_at)
ORDER BY response_at ASC
`

// Finds rows that have responded but haven't been synced OR have changed since sync.
// datetime() normalizes both sides so RFC3339 and space-separated formats compare correctly.
//
//	SELECT invite_code, name, max_adults, max_kids, confirmed_adults, confirmed_kids, dietary_info, message_for_us, song_request, response_at, sheet_row, location, travel_bus_to, travel_pickup, travel_arrival_flight, travel_bus_return, travel_hotel, travel_notes, travel_cocktail, travel_brunch, travel_return_detail, travel_updated_at, created_at, updated_at FROM invites
//	WHERE response_at IS NOT NULL
//	  AND datetime(response_at) > datetime(updated_at)
//	ORDER BY response_at ASC
func (q *Queries) GetPendingSyncInvites(ctx context.Context) ([]*Invite, error) {
	rows, err := q.query(ctx, q.getPendingSyncInvitesStmt, GetPendingSyncInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Invite{}
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.InviteCode,
			&i.Name,
			&i.MaxAdults,
			&i.MaxKids,
			&i.ConfirmedAdults,
			&i.ConfirmedKids,
			&i.DietaryInfo,
			&i.MessageForUs,
			&i.SongRequest,
			&i.ResponseAt,
			&i.SheetRow,
			&i.Location,
			&i.TravelBusTo,
			&i.TravelPickup,
			&i.TravelArrivalFlight,
			&i.TravelBusReturn,
			&i.TravelHotel,
			&i.TravelNotes,
			&i.TravelCocktail,
			&i.TravelBrunch,
			&i.TravelReturnDetail,
			&i.TravelUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetScheduleEvents = `-- name: GetScheduleEvents :many

SELECT id, start_time, end_time, event_name_es, event_name_en, event_name_ca, location, description_es, description_en, description_ca, updated_at FROM schedule_events
ORDER BY start_time ASC
`

// =====================
// Schedule Events Queries
// =====================
// Returns all schedule events ordered by start time.
// Only public events are stored in the DB (filtered during sync).
//
//	SELECT id, start_time, end_time, event_name_es, event_name_en, event_name_ca, location, description_es, description_en, description_ca, updated_at FROM schedule_events
//	ORDER BY start_time ASC
func (q *Queries) GetScheduleEvents(ctx context.Context) ([]*ScheduleEvent, error) {
	rows, err := q.query(ctx, q.getScheduleEventsStmt, GetScheduleEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ScheduleEvent{}
	for rows.Next() {
		var i ScheduleEvent
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.EventNameEs,
			&i.EventNameEn,
			&i.EventNameCa,
			&i.Location,
			&i.DescriptionEs,
			&i.DescriptionEn,
			&i.DescriptionCa,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const InsertScheduleEvent = `-- name: InsertScheduleEvent :exec
INSERT INTO schedule_events (
    start_time, end_time,
    event_name_es, event_name_en, event_name_ca,
    location,
    description_es, description_en, description_ca,
    updated_at
) VALUES (
    ?, ?,
    ?, ?, ?,
    ?,
    ?, ?, ?,
    datetime('now', 'utc')
)
`

type InsertScheduleEventParams struct {
	StartTime     string  `json:"start_time"`
	EndTime       *string `json:"end_time"`
	EventNameEs   string  `json:"event_name_es"`
	EventNameEn   string  `json:"event_name_en"`
	EventNameCa   string  `json:"event_name_ca"`
	Location      string  `json:"location"`
	DescriptionEs string  `json:"description_es"`
	DescriptionEn string  `json:"description_en"`
	DescriptionCa string  `json:"description_ca"`
}

// Inserts a single schedule event during sync.
//
//	INSERT INTO schedule_events (
//	    start_time, end_time,
//	    event_name_es, event_name_en, event_name_ca,
//	    location,
//	    description_es, description_en, description_ca,
//	    updated_at
//	) VALUES (
//	    ?, ?,
//	    ?, ?, ?,
//	    ?,
//	    ?, ?, ?,
//	    datetime('now', 'utc')
//	)
func (q *Queries) InsertScheduleEvent(ctx context.Context, arg *InsertScheduleEventParams) error {
	_, err := q.exec(ctx, q.insertScheduleEventStmt, InsertScheduleEvent,
		arg.StartTime,
		arg.EndTime,
		arg.EventNameEs,
		arg.EventNameEn,
		arg.EventNameCa,
		arg.Location,
		arg.DescriptionEs,
		arg.DescriptionEn,
		arg.DescriptionCa,
	)
	return err
}

const MarkInviteSynced = `-- name: MarkInviteSynced :exec
UPDATE invites
SET
    updated_at = datetime('now', 'utc')
WHERE invite_code = ?
`

// MarkInviteSynced
//
//	UPDATE invites
//	SET
//	    updated_at = datetime('now', 'utc')
//	WHERE invite_code = ?
func (q *Queries) MarkInviteSynced(ctx context.Context, inviteCode string) error {
	_, err := q.exec(ctx, q.markInviteSyncedStmt, MarkInviteSynced, inviteCode)
	return err
}

const UpdateRSVP = `-- name: UpdateRSVP :exec
UPDATE invites
SET
    confirmed_adults = ?1,
    confirmed_kids   = ?2,
    dietary_info     = ?3,
    message_for_us   = ?4,
    song_request     = ?5,
    response_at      = datetime('now', 'utc')-- Mark as needing sync
WHERE
    invite_code = ?6
    -- Validation Logic:
    AND ?1 <= max_adults
    AND ?2   <= max_kids
`

type UpdateRSVPParams struct {
	InputConfirmedAdults int64  `json:"input_confirmed_adults"`
	InputConfirmedKids   int64  `json:"input_confirmed_kids"`
	InputDietaryInfo     string `json:"input_dietary_info"`
	InputMessage         string `json:"input_message"`
	InputSong            string `json:"input_song"`
	InputInviteCode      string `json:"input_invite_code"`
}

// Updates RSVP details and forces a sync (synced_at = NULL).
//
//	UPDATE invites
//	SET
//	    confirmed_adults = ?1,
//	    confirmed_kids   = ?2,
//	    dietary_info     = ?3,
//	    message_for_us   = ?4,
//	    song_request     = ?5,
//	    response_at      = datetime('now', 'utc')-- Mark as needing sync
//	WHERE
//	    invite_code = ?6
//	    -- Validation Logic:
//	    AND ?1 <= max_adults
//	    AND ?2   <= max_kids
func (q *Queries) UpdateRSVP(ctx context.Context, arg *UpdateRSVPParams) error {
	_, err := q.exec(ctx, q.updateRSVPStmt, UpdateRSVP,
		arg.InputConfirmedAdults,
		arg.InputConfirmedKids,
		arg.InputDietaryInfo,
		arg.InputMessage,
		arg.InputSong,
		arg.InputInviteCode,
	)
	return err
}

const UpdateTravelInfo = `-- name: UpdateTravelInfo :exec
UPDATE invites
SET
    travel_bus_to        = ?1,
    travel_pickup        = ?2,
    travel_arrival_flight = ?3,
    travel_bus_return    = ?4,
    travel_hotel         = ?5,
    travel_notes         = ?6,
    travel_cocktail      = ?7,
    travel_brunch        = ?8,
    travel_return_detail = ?9,
    travel_updated_at    = datetime('now', 'utc'),
    response_at          = datetime('now', 'utc')
WHERE invite_code = ?10
`

type UpdateTravelInfoParams struct {
	InputBusTo         string `json:"input_bus_to"`
	InputPickup        string `json:"input_pickup"`
	InputArrivalFlight string `json:"input_arrival_flight"`
	InputBusReturn     string `json:"input_bus_return"`
	InputHotel         string `json:"input_hotel"`
	InputNotes         string `json:"input_notes"`
	InputCocktail      string `json:"input_cocktail"`
	InputBrunch        string `json:"input_brunch"`
	InputReturnDetail  string `json:"input_return_detail"`
	InputInviteCode    string `json:"input_invite_code"`
}

// Updates travel fields and bumps response_at so GetPendingSyncInvites picks it up.
//
//	UPDATE invites
//	SET
//	    travel_bus_to        = ?1,
//	    travel_pickup        = ?2,
//	    travel_arrival_flight = ?3,
//	    travel_bus_return    = ?4,
//	    travel_hotel         = ?5,
//	    travel_notes         = ?6,
//	    travel_cocktail      = ?7,
//	    travel_brunch        = ?8,
//	    travel_return_detail = ?9,
//	    travel_updated_at    = datetime('now', 'utc'),
//	    response_at          = datetime('now', 'utc')
//	WHERE invite_code = ?10
func (q *Queries) UpdateTravelInfo(ctx context.Context, arg *UpdateTravelInfoParams) error {
	_, err := q.exec(ctx, q.updateTravelInfoStmt, UpdateTravelInfo,
		arg.InputBusTo,
		arg.InputPickup,
		arg.InputArrivalFlight,
		arg.InputBusReturn,
		arg.InputHotel,
		arg.InputNotes,
		arg.InputCocktail,
		arg.InputBrunch,
		arg.InputReturnDetail,
		arg.InputInviteCode,
	)
	return err
}

const UpsertInvite = `-- name: UpsertInvite :exec
INSERT INTO invites (
    invite_code, name, max_adults, max_kids,
    confirmed_adults, confirmed_kids, dietary_info, message_for_us, song_request, response_at,
    sheet_row, location,
    travel_bus_to, travel_pickup, travel_arrival_flight, travel_bus_return,
    travel_hotel, travel_notes, travel_cocktail, travel_brunch, travel_return_detail, travel_updated_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    datetime('now', 'utc')
)
ON CONFLICT(invite_code) DO UPDATE SET
    -- Master data: always follow the sheet.
    name                  = excluded.name,
    max_adults            = excluded.max_adults,
    max_kids              = excluded.max_kids,
    sheet_row             = excluded.sheet_row,
    location              = excluded.location,
    -- Guest-entered fields: only overwrite when no local changes are pending.
    -- "pending" = response_at IS NOT NULL AND response_at > updated_at.
    -- datetime() normalizes both sides so RFC3339 and space-separated formats compare correctly.
    confirmed_adults      = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
                                 THEN excluded.confirmed_adults ELSE invites.confirmed_adults END,
    confirmed_kids        = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
                                 THEN excluded.confirmed_kids ELSE invites.confirmed_kids END,
    dietary_info          = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
                                 THEN excluded.dietary_info ELSE invites.dietary_info END,
    message_for_us        = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
                                 THEN excluded.message_for_us ELSE invites.message_for_us END,
    song_request          = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
                                 THEN excluded.song_request ELSE invites.song_request END,
    response_at           = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
                                 THEN excluded.response_at ELSE invites.response_at END,
    travel_bus_to         = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
                                 THEN excluded.travel_bus_to ELSE invites.travel_bus_to END,
    travel_pickup         = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
                                 THEN excluded.travel_pickup ELSE invites.travel_pickup END,
    travel_arrival_flight = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
                                 THEN excluded.travel_arrival_flight ELSE invites.travel_arrival_flight END,
    travel_bus_return     = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
                                 THEN excluded.travel_bus_return ELSE invites.travel_bus_return END,
    travel_hotel          = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
                                 THEN excluded.travel_hotel ELSE invites.travel_hotel END,
    travel_notes          = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
                                 THEN excluded.travel_notes ELSE invites.travel_notes END,
    travel_cocktail       = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
                                 THEN excluded.travel_cocktail ELSE invites.travel_cocktail END,
    travel_brunch         = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
                                 THEN excluded.travel_brunch ELSE invites.travel_brunch END,
    travel_return_detail  = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
                                 THEN excluded.travel_return_detail ELSE invites.travel_return_detail END,
    travel_updated_at     = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
                                 THEN excluded.travel_updated_at ELSE invites.travel_updated_at END,
    updated_at            = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
                                 THEN datetime('now', 'utc') ELSE invites.updated_at END
`

type UpsertInviteParams struct {
	InviteCode          string     `json:"invite_code"`
	Name                string     `json:"name"`
	MaxAdults           int64      `json:"max_adults"`
	MaxKids             int64      `json:"max_kids"`
	ConfirmedAdults     int64      `json:"confirmed_adults"`
	ConfirmedKids       int64      `json:"confirmed_kids"`
	DietaryInfo         string     `json:"dietary_info"`
	MessageForUs        string     `json:"message_for_us"`
	SongRequest         string     `json:"song_request"`
	ResponseAt          *time.Time `json:"response_at"`
	SheetRow            *int64     `json:"sheet_row"`
	Location            string     `json:"location"`
	TravelBusTo         string     `json:"travel_bus_to"`
	TravelPickup        string     `json:"travel_pickup"`
	TravelArrivalFlight string     `json:"travel_arrival_flight"`
	TravelBusReturn     string     `json:"travel_bus_return"`
	TravelHotel         string     `json:"travel_hotel"`
	TravelNotes         string     `json:"travel_notes"`
	TravelCocktail      string     `json:"travel_cocktail"`
	TravelBrunch        string     `json:"travel_brunch"`
	TravelReturnDetail  string     `json:"travel_return_detail"`
	TravelUpdatedAt     *time.Time `json:"travel_updated_at"`
}

// Syncs Master Data from Google Sheets -> DB.
// Master data (name, limits, location, sheet_row) always updates.
// Guest-entered fields (RSVP, travel) are protected while pending sync.
// datetime() around column refs normalizes RFC3339 vs space-separated timestamps
// so the pending-changes guard compares correctly.
//
//	INSERT INTO invites (
//	    invite_code, name, max_adults, max_kids,
//	    confirmed_adults, confirmed_kids, dietary_info, message_for_us, song_request, response_at,
//	    sheet_row, location,
//	    travel_bus_to, travel_pickup, travel_arrival_flight, travel_bus_return,
//	    travel_hotel, travel_notes, travel_cocktail, travel_brunch, travel_return_detail, travel_updated_at,
//	    updated_at
//	) VALUES (
//	    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
//	    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
//	    datetime('now', 'utc')
//	)
//	ON CONFLICT(invite_code) DO UPDATE SET
//	    -- Master data: always follow the sheet.
//	    name                  = excluded.name,
//	    max_adults            = excluded.max_adults,
//	    max_kids              = excluded.max_kids,
//	    sheet_row             = excluded.sheet_row,
//	    location              = excluded.location,
//	    -- Guest-entered fields: only overwrite when no local changes are pending.
//	    -- "pending" = response_at IS NOT NULL AND response_at > updated_at.
//	    -- datetime() normalizes both sides so RFC3339 and space-separated formats compare correctly.
//	    confirmed_adults      = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
//	                                 THEN excluded.confirmed_adults ELSE invites.confirmed_adults END,
//	    confirmed_kids        = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
//	                                 THEN excluded.confirmed_kids ELSE invites.confirmed_kids END,
//	    dietary_info          = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
//	                                 THEN excluded.dietary_info ELSE invites.dietary_info END,
//	    message_for_us        = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
//	                                 THEN excluded.message_for_us ELSE invites.message_for_us END,
//	    song_request          = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
//	                                 THEN excluded.song_request ELSE invites.song_request END,
//	    response_at           = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
//	                                 THEN excluded.response_at ELSE invites.response_at END,
//	    travel_bus_to         = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
//	                                 THEN excluded.travel_bus_to ELSE invites.travel_bus_to END,
//	    travel_pickup         = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
//	                                 THEN excluded.travel_pickup ELSE invites.travel_pickup END,
//	    travel_arrival_flight = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
//	                                 THEN excluded.travel_arrival_flight ELSE invites.travel_arrival_flight END,
//	    travel_bus_return     = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
//	                                 THEN excluded.travel_bus_return ELSE invites.travel_bus_return END,
//	    travel_hotel          = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
//	                                 THEN excluded.travel_hotel ELSE invites.travel_hotel END,
//	    travel_notes          = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
//	                                 THEN excluded.travel_notes ELSE invites.travel_notes END,
//	    travel_cocktail       = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
//	                                 THEN excluded.travel_cocktail ELSE invites.travel_cocktail END,
//	    travel_brunch         = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
//	                                 THEN excluded.travel_brunch ELSE invites.travel_brunch END,
//	    travel_return_detail  = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
//	                                 THEN excluded.travel_return_detail ELSE invites.travel_return_detail END,
//	    travel_updated_at     = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
//	                                 THEN excluded.travel_updated_at ELSE invites.travel_updated_at END,
//	    updated_at            = CASE WHEN invites.response_at IS NULL OR datetime(invites.response_at) <= datetime(invites.updated_at)
//	                                 THEN datetime('now', 'utc') ELSE invites.updated_at END
func (q *Queries) UpsertInvite(ctx context.Context, arg *UpsertInviteParams) error {
	_, err := q.exec(ctx, q.upsertInviteStmt, UpsertInvite,
		arg.InviteCode,
		arg.Name,
		arg.MaxAdults,
		arg.MaxKids,
		arg.ConfirmedAdults,
		arg.ConfirmedKids,
		arg.DietaryInfo,
		arg.MessageForUs,
		arg.SongRequest,
		arg.ResponseAt,
		arg.SheetRow,
		arg.Location,
		arg.TravelBusTo,
		arg.TravelPickup,
		arg.TravelArrivalFlight,
		arg.TravelBusReturn,
		arg.TravelHotel,
		arg.TravelNotes,
		arg.TravelCocktail,
		arg.TravelBrunch,
		arg.TravelReturnDetail,
		arg.TravelUpdatedAt,
	)
	return err
}
