// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
)

const DeleteInvite = `-- name: DeleteInvite :exec
    -- protecting local RSVP changes that haven't been pushed to the sheet yet.



DELETE FROM invites
WHERE invite_code = ?
`

// Note: The WHERE clause prevents updates when synced_at IS NULL,
// HARD DELETE: This permanently removes the row.
//
//	    -- protecting local RSVP changes that haven't been pushed to the sheet yet.
//
//
//
//	DELETE FROM invites
//	WHERE invite_code = ?
func (q *Queries) DeleteInvite(ctx context.Context, inviteCode string) error {
	_, err := q.exec(ctx, q.deleteInviteStmt, DeleteInvite, inviteCode)
	return err
}

const GetInviteByInviteCode = `-- name: GetInviteByInviteCode :one
SELECT invite_code, name, max_adults, max_kids, confirmed_adults, confirmed_kids, dietary_info, message_for_us, song_request, response_at, sheet_row, created_at, updated_at FROM invites WHERE invite_code = ?
`

// GetInviteByInviteCode
//
//	SELECT invite_code, name, max_adults, max_kids, confirmed_adults, confirmed_kids, dietary_info, message_for_us, song_request, response_at, sheet_row, created_at, updated_at FROM invites WHERE invite_code = ?
func (q *Queries) GetInviteByInviteCode(ctx context.Context, inviteCode string) (*Invite, error) {
	row := q.queryRow(ctx, q.getInviteByInviteCodeStmt, GetInviteByInviteCode, inviteCode)
	var i Invite
	err := row.Scan(
		&i.InviteCode,
		&i.Name,
		&i.MaxAdults,
		&i.MaxKids,
		&i.ConfirmedAdults,
		&i.ConfirmedKids,
		&i.DietaryInfo,
		&i.MessageForUs,
		&i.SongRequest,
		&i.ResponseAt,
		&i.SheetRow,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetPendingSyncInvites = `-- name: GetPendingSyncInvites :many
SELECT invite_code, name, max_adults, max_kids, confirmed_adults, confirmed_kids, dietary_info, message_for_us, song_request, response_at, sheet_row, created_at, updated_at FROM invites
WHERE response_at IS NOT NULL
  AND response_at > updated_at
ORDER BY response_at ASC
`

// Finds rows that have responded but haven't been synced OR have changed since sync.
//
//	SELECT invite_code, name, max_adults, max_kids, confirmed_adults, confirmed_kids, dietary_info, message_for_us, song_request, response_at, sheet_row, created_at, updated_at FROM invites
//	WHERE response_at IS NOT NULL
//	  AND response_at > updated_at
//	ORDER BY response_at ASC
func (q *Queries) GetPendingSyncInvites(ctx context.Context) ([]*Invite, error) {
	rows, err := q.query(ctx, q.getPendingSyncInvitesStmt, GetPendingSyncInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Invite{}
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.InviteCode,
			&i.Name,
			&i.MaxAdults,
			&i.MaxKids,
			&i.ConfirmedAdults,
			&i.ConfirmedKids,
			&i.DietaryInfo,
			&i.MessageForUs,
			&i.SongRequest,
			&i.ResponseAt,
			&i.SheetRow,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkInviteSynced = `-- name: MarkInviteSynced :exec
UPDATE invites
SET
    updated_at = datetime('now', 'utc')
WHERE invite_code = ?
`

// MarkInviteSynced
//
//	UPDATE invites
//	SET
//	    updated_at = datetime('now', 'utc')
//	WHERE invite_code = ?
func (q *Queries) MarkInviteSynced(ctx context.Context, inviteCode string) error {
	_, err := q.exec(ctx, q.markInviteSyncedStmt, MarkInviteSynced, inviteCode)
	return err
}

const UpdateRSVP = `-- name: UpdateRSVP :exec
UPDATE invites
SET
    confirmed_adults = ?1,
    confirmed_kids   = ?2,
    dietary_info     = ?3,
    message_for_us   = ?4,
    song_request     = ?5,
    response_at      = datetime('now', 'utc')-- Mark as needing sync
WHERE
    invite_code = ?6
    -- Validation Logic:
    AND ?1 <= max_adults
    AND ?2   <= max_kids
`

type UpdateRSVPParams struct {
	InputConfirmedAdults int64  `json:"input_confirmed_adults"`
	InputConfirmedKids   int64  `json:"input_confirmed_kids"`
	InputDietaryInfo     string `json:"input_dietary_info"`
	InputMessage         string `json:"input_message"`
	InputSong            string `json:"input_song"`
	InputInviteCode      string `json:"input_invite_code"`
}

// Updates RSVP details and forces a sync (synced_at = NULL).
//
//	UPDATE invites
//	SET
//	    confirmed_adults = ?1,
//	    confirmed_kids   = ?2,
//	    dietary_info     = ?3,
//	    message_for_us   = ?4,
//	    song_request     = ?5,
//	    response_at      = datetime('now', 'utc')-- Mark as needing sync
//	WHERE
//	    invite_code = ?6
//	    -- Validation Logic:
//	    AND ?1 <= max_adults
//	    AND ?2   <= max_kids
func (q *Queries) UpdateRSVP(ctx context.Context, arg *UpdateRSVPParams) error {
	_, err := q.exec(ctx, q.updateRSVPStmt, UpdateRSVP,
		arg.InputConfirmedAdults,
		arg.InputConfirmedKids,
		arg.InputDietaryInfo,
		arg.InputMessage,
		arg.InputSong,
		arg.InputInviteCode,
	)
	return err
}

const UpsertInvite = `-- name: UpsertInvite :exec
INSERT INTO invites (
    invite_code, name, max_adults, max_kids, confirmed_adults, sheet_row, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, datetime('now', 'utc')
)
ON CONFLICT(invite_code) DO UPDATE SET
    name       = excluded.name,
    max_adults = excluded.max_adults,
    max_kids   = excluded.max_kids,
    sheet_row  = excluded.sheet_row,
    confirmed_adults = excluded.confirmed_adults,
    updated_at = excluded.updated_at
WHERE invites.response_at IS NULL OR invites.response_at <= invites.updated_at
`

type UpsertInviteParams struct {
	InviteCode      string `json:"invite_code"`
	Name            string `json:"name"`
	MaxAdults       int64  `json:"max_adults"`
	MaxKids         int64  `json:"max_kids"`
	ConfirmedAdults int64  `json:"confirmed_adults"`
	SheetRow        *int64 `json:"sheet_row"`
}

// Syncs Master Data from Google Sheets -> DB.
// Skips updates if invite has unsynced local changes (synced_at IS NULL).
//
//	INSERT INTO invites (
//	    invite_code, name, max_adults, max_kids, confirmed_adults, sheet_row, updated_at
//	) VALUES (
//	    ?, ?, ?, ?, ?, ?, datetime('now', 'utc')
//	)
//	ON CONFLICT(invite_code) DO UPDATE SET
//	    name       = excluded.name,
//	    max_adults = excluded.max_adults,
//	    max_kids   = excluded.max_kids,
//	    sheet_row  = excluded.sheet_row,
//	    confirmed_adults = excluded.confirmed_adults,
//	    updated_at = excluded.updated_at
//	WHERE invites.response_at IS NULL OR invites.response_at <= invites.updated_at
func (q *Queries) UpsertInvite(ctx context.Context, arg *UpsertInviteParams) error {
	_, err := q.exec(ctx, q.upsertInviteStmt, UpsertInvite,
		arg.InviteCode,
		arg.Name,
		arg.MaxAdults,
		arg.MaxKids,
		arg.ConfirmedAdults,
		arg.SheetRow,
	)
	return err
}
